---
title: "Formigas"
description: "Um plano inusitado para matar todas as formigas do mundo."
author: William Amorim
date: 2017-02-02
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Júlia empurrava lentamente o pesado carrinho de compras pelos corredores do supermercado quando percebeu que não fazia ideia do que estava fazendo.

— Cara, o que a gente vai fazer mesmo? — ela balbuciou para o homem que a acompanhava. Sua língua deslizava pelos dentes, sentindo um gosto estranho na boca. Um gosto familiar, mas estranho.

— Matar todas as formigas do mundo — ele respondeu, com toda a calma possível.

— Sério? É uma ótima ideia! Mas por que a gente vai fazer isso? — Ela hesitou por um segundo. — Aliás, quem é você mesmo?

— Se esqueceu de novo? — o homem perguntou, apesar de já saber a resposta.

Júlia o encarou com seus grandes olhos lilases e fez que sim.

— A gente se conheceu na festa do seu irmão. Estávamos bebendo cerveja e conversando sobre cinema quando uma das suas amigas lhe ofereceu um comprimido laranja. Você engoliu o comprimido e começou a dançar de um jeito bem esquisito. Depois me puxou de lado e disse que havia tido a melhor ideia da sua vida. Eu perguntei qual era e você respondeu que deveríamos matar todas as formigas do mundo. Eu disse que não era uma boa ideia, mas você me puxou para fora da festa e me trouxe até este supermercado. Então você pegou esse carrinho e jogou nele todos os inseticidas da prateleira. Estávamos indo para o caixa quando eu lhe disse que não sou deste planeta. Você apertou a minha bochecha, pegou *esta* barra de manteiga *daquele* refrigerador e deu uma grande mordida.

Júlia olhou para uma das mãos que não empurravam o carrinho e viu uma barra de manteiga começando a derreter.

— Argh! Eu odeio manteiga! — disse a mulher, fazendo careta e jogando a barra de gordura por cima da prateleira. — Mas e depois?

— Sete segundos depois você perguntou o que a gente ia fazer.

— E o que era mesmo?

— Matar todas as formigas do mundo.

— Isso! Ótima ideia! Quanto tempo você acha que vamos levar para matar todas elas?

— Sendo otimista?

— Sim, sempre! — respondeu Júlia, animada.

— Se elas pararem de se reproduzir exatamente agora, mais ou menos 6 milhões de anos.

— É um bocado de tempo — Júlia refletiu.

O homem não disse nada.

— Viu, qual é o seu nome mesmo?

— Você vem me chamando de Lucas a noite toda, mas eu nunca disse o meu nome.

— Não, não. Você não tem cara de Lucas. — Júlia pensou por um instante e estalou os dedos. — Dan! Dan é um nome melhor para você.

Dan fez questão de mostrar um sorriso, e Júlia sorriu de volta.

— Cara, onde estão os caixas? A gente não chega nunca!

— É porque essa já é a quinta volta que damos nesses dois corredores — explicou Dan.

— E por que estamos fazendo isso, Dan?

— Só estou te seguindo.

Júlia mostrou a língua para Dan e saiu correndo em câmera lenta, agora com todas as mãos empurrando o carrinho pesado. Já no caixa, Dan a alcançou.

— Achei! — ela disse contente. — Escuta, você tem dinheiro para comprar tudo isso? Eu esqueci de pegar a minha bolsa.

— Não se preocupe, eu pago — afirmou Dan.

Júlia começou a colocar os frascos de inseticida na esteira enquanto, discretamente, olhava de canto de olho para o homem com cara de cansado atrás da caixa registradora, esperando que ele fizesse algum comentário.

— Não se preocupe — disse o homem com cara de cansado atrás da caixa registradora após perceber os olhares nada discretos de Júlia. — Depois de 20 anos no turno da madrugada, nenhuma compra me surpreende mais. Vão querer sacola?

Júlia mordeu o lábio e olhou para Dan, que assentiu:

— Dezesseis sacolas, por favor.

Dan pagou a compra nada barata, e os dois saíram do supermercado carregando as sacolas de inseticida. 

— Agora precisamos pensar na logística. Por onde começamos? — perguntou Júlia, já na calçada.

— Você já escutou a história do bêbado em cima do muro?

Júlia balançou a cabeça, claramente curiosa.

— Dois amigos estavam numa festa e, após beber um pouco além da conta, um deles subiu num muro e começou a esticar a mão na direção do céu. Seu amigo, com medo de ele cair e se machucar, pediu para que descesse de lá. O rapaz em cima do muro se negou, e o seu amigo continuou insistindo. Após muita insistência e negativa, o amigo sóbrio resolveu perguntar o que ele estava fazendo em cima daquele muro. O amigo bêbado explicou que queria pegar a lua e só desceria quando conseguisse. O rapaz no chão deu uma risada e esticou a mão para o amigo, dizendo: "Se é esse o problema, pode descer tranquilo. A essa distância, a altura do muro não vai te fazer diferença nenhuma. "

A mulher olhou para Dan e riu sem ter certeza se tinha entendido.

— Olha! — Júlia gritou, apontando. — É o parque que fica aberto a noite toda. Vamos começar por lá.

Ela apertou o passo na direção do parque e Dan a seguiu.

Eles deram algumas voltas pelo parque, passando por jovens que bebiam e escutavam música e outros que jogavam um esporte muito parecido com basquete, só que mais complicado. Júlia sentiu uma leve tontura, e eles sentaram na grama de uma pequena colina.

— Sabe, Dan, eu estive meio triste esses dias.

Dan não disse nada, mas demonstrou que prestava atenção.

— O idiota do meu namorado... ex-namorado... terminou comigo. E o pior é que eu sinto falta dele.

— Vai passar, não se preocupe — disse Dan, tentando confortá-la.

— É, provavelmente. — Júlia deitou na grama e passou a admirar o céu. — Eu só queria que fosse rápido, tipo agora... Olha, Dan, como a lua está bonita!

Dan olhou para o satélite, que brilhava em vermelho no céu estrelado.

— Não é à toa que o menino da sua história queria pegá-la — Júlia continuou.

— Não, não era — concordou Dan.

— Escuta, você é mesmo de outro planeta?

— Sou.

— Legal. Que bom que as pessoas no seu planeta também têm cartão de crédito.

— Esse não sou eu — explicou Dan, apontando para si mesmo. — Só peguei esse corpo emprestado.

Júlia riu.

— Você é muito besta, Dan.

Júlia soltou um longo bocejo, se espreguiçando. Ao esticar as pernas, acabou chutando uma das sacolas, fazendo alguns frascos rolarem pela colina.

— O idiota do meu namo... ex-namorado... colecionava aquelas fazendas de formigas. Ele tinha, sei lá, umas 50 delas. Ele tratava aqueles bichinhos verdes nojentos como filhos... — A mulher deu um sorriso triste e fechou os olhos, bocejando novamente. — Um idiota... um grande idiota...

— A gente pode começar com as formigas dele — Dan sugeriu.

— Sim... É uma ótima ideia, Dan... — concordou Júlia, sonolenta.

— Vamos voltar para a festa? — Dan sugeriu.

— Uhum...

Dan se abaixou, e Júlia subiu em suas costas, se segurando em sua barriga e em seu pescoço.

— E os inseticidas? A gente ainda não matou as formigas — Júlia resmungou quando Dan começou a andar.

— Não se preocupe — ele respondeu. — Com o tempo, todas as formigas do mundo vão morrer sozinhas. 

---

**Motivação**: desafio semanal da página "Gente que escreve", no Facebook, com o tema "formigas". Na época, estava escrevendo contos sobre um personagem que viajava para diferentes mundos para colecionar histórias.

