---
title: "Abandonados"
description: "Dois companheiros a espera de um retorno."
author:  William Amorim
date: 2017-04-20
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


A armadura prateada de Arthur brilhava sob o persistente sol da tarde, gotas de suor escapavam do seu rosto e pingavam na grama verde. Seus dentes rangiam, os olhos piscavam menos que o normal. A mão direita mexia inconscientemente no cabo da espada; a esquerda esperava um comando.

— Merda! — ele exclamou, amaldiçoando a si mesmo por ter deixado as coisas chegarem àquele ponto.

Arthur não era um cavaleiro formidável, mas entendia uma coisa ou outra sobre acertar seus inimigos com uma espada antes que eles o acertassem. Também montava bem, apesar de não ter uma boa relação com o seu cavalo. Para ser mais exato, eles se odiavam. Já com o arco-e-flecha, era uma negação. Completamente ridículo. Inútil ao ponto de o ditado "Você é pior nisso do que Arthur com um arco-e-flecha" ser conhecido em vilarejos onde ninguém nem mesmo sabia quem ele era.

Mas essas habilidades não estavam em jogo agora. O seu único recurso era o cérebro, a inteligência, a capacidade de escolher bem o próximo movimento. O rei dependia disso.

— O que está esperando? — provocou o oponente.

— Cala a boca! — esbravejou Arthur.

Sua cabeça estava a mil. Diferentes cenários dançavam na sua mente. Possibilidades, receios, arrependimentos... Mas não havia mais tempo para pensar, precisava agir. Olhou fixamente para o cavalo negro, seu cúmplice no que viria a seguir, torcendo para que o seu plano funcionasse. Com um movimento seco, ele se inclinou para frente e ameaçou a rainha inimiga.

O oponente o encarou, tentando entender o porquê daquela ação desesperada.

— Você não deveria ter feito isso, Arthur.

Arthur o olhou com uma cara séria e fez um sinal para que ele parasse de uma vez por todas de encher o saco. O suor pingava mais intensamente, caindo ao lado do elmo que tirou por causa do calor.

— Tudo bem, tudo bem — assentiu o oponente, empurrando o bispo com um dedo. — Xeque-mate!

Arthur arregalou os olhos, entendendo o que tinha acontecido, se xingando em pensamento.

— Mas que merda! — ele esbravejou, batendo a mão no tabuleiro. As peças brancas e pretas voaram para todos os lados.

— Calma! — pediu o vitorioso adversário. — Você até que jogou melhor dessa vez.

— *Você até que jogou melhor dessa vez* — repetiu Arthur, em tom de deboche. — Cala a boca! Já é a sétima partida que você ganha! — Ele bicou o elmo para longe e completou: — E você é uma porcaria de um dragão!

O dragão suspirou, soltando ar quente pelas narinas.

— Ei! Para com isso! — reclamou Arthur, abanando desesperadamente o ar. — Já não basta esse sol infernal na minha cabeça e você ainda tem que jogar vapor em mim?

— Tira essa armadura — retrucou o dragão. — Você está cozinhando aí dentro.

— Nunca! — Arthur estava fora de si, o que, na verdade, era normal. — Ele pode voltar a qualquer momento. Não vou deixar você me pegar desprevenido.

— Que seja! — bufou o dragão.

Arthur respirou fundo, tentando se recompor. Não conseguiu.

— E vamos jogar outro jogo. Já cansei dessa porcaria — queixou-se, chutando agora a cavalo preto para o alto.

O seu cavalo, que não era preto, mas sim um alazão, relinchou ao fundo, onde pastava à sombra de um carvalho.

— E você cala a boca também! Ninguém pediu a sua opinião — berrou Arthur. — Cavalo idiota...

— Calma, camarada. Você está muito nervoso. Faz mal para o fígado. Vamos jogar outra coisa. O que vai ser agora? Damas?

— Damas? De novo? Não tem outro jogo? — Arthur pensou por um instante. — Um jogo de cartas talvez?

— Você destruiu o meu baralho — lembrou o dragão, fechando a cara.

— Ah — exclamou Arthur envergonhado. Lembranças suas atacando a espadadas um *deck* de cartas passaram rapidamente pela sua mente. — Você não tem outro?

— Tenho, mas está lá na montanha.

— Você não pode voar lá rapidinho e...

— Não! — interrompeu o dragão. — Você mesmo disse que ele pode voltar a qualquer momento. E se eu não estiver aqui quando ele chegar?

Arthur soltou o ar como se tivesse aberto as mãos e largado duas toneladas no chão.

— Que seja... Quer saber? Vou fumar um cachimbo e relaxar um pouco.

— Talvez seja uma boa ideia — concordou o dragão.

— *Talvez seja uma boa ideia* — retrucou Arthur, de novo com deboche. — Dragão cretino... — disse baixinho, para si mesmo.

O irritado cavaleiro assobiou, convocando o cavalo. O equino virou a cabeça para ele, demonstrando que tinha escudando o chamado, e o ignorou. Arthur se impressionou por, após três anos de insolências, ainda esperar que o animal o respeitasse. Ele moveu a armadura colina acima, levantando poeira ao bater os pés no chão, sem vergonha de esconder o quanto estava contrariado. Ao se aproximar, o cavalo levantou o rabo e despejou porções de esterco fresco na grama, aromatizando o ar em volta da árvore. Arthur pensou em palavrões que fariam até os pais mais liberais tampar os ouvidos de seus filhos e então, sem respirar, pegou seu cachimbo na bolsa de garupa.

— Se "cuida bem do meu cavalo" não tivesse sido as últimas palavras da minha mãe, eu já teria te vendido pela pior proposta que me oferecessem — fez questão de dizer ao cavalo, antes de dar as costas e descer a colina.

— Já faz quanto tempo? — perguntou o dragão, assim que Arthur se aproximou o suficiente.

— Muito mais do que eu gostaria — ele divagou, sentando na rocha onde estava o tabuleiro.

— Será que aconteceu alguma coisa com ele? Ele pode ter se mudado ou estar num hospital. Ou até mesmo...

— Não aconteceu nada. Ele apenas nos abandonou por qualquer motivo.

Arthur levou o cachimbo à boca e acendeu o fumo.

— Mas por quê? Nós estávamos bem. Eu queimei o vilarejo como nunca e a sua luta com os lobos foi magnífica. Simplesmente magnífica!

— Olha, não adianta ficar pensando nisso — aconselhou o cavaleiro, soltando fumaça pelo nariz. — Às vezes acontece e pronto. Ele pode estar muito ocupado ou encontrou outra coisa para ler, sei lá. Não fizemos nada de errado, ok? Vamos esperar aqui até ele voltar ou outra pessoa pegar o livro. Só queria que ele não tivesse parado bem na merda do "E o sol ardia no céu...".

O dragão abaixou os olhos, concordando com a cabeça. Os dois permaneceram em silêncio, contemplando a fumaça que desaparecia no ar.

— Sabe qual a parte da história que eu menos gosto? — perguntou o dragão, quase sem querer.

— A que eu monto nas suas costas e te chamo de lagartixa voadora? — o cavaleiro perguntou com um sorriso.

— Não, não. É a par... Espera! Isso não acontece!

— Não, mas deveria.

Arthur colocou o cachimbo de lado e se sentou na grama, de frente para o companheiro. O dragão continuou:

— A parte que eu menos gosto é o final.

— Só por que eu te derroto justamente com uma flechada?

— Eu admito que fico no mínimo desgostoso com isso, mas o problema não é o que acontece em si. É outra coisa.

— O que é então?

— O problema é não existir nada depois. A gente passa tanto tempo com uma pessoa, dando o nosso máximo para ela se divertir, se emocionar. Ficamos atentos a cada reação, vendo se ela gostou ou não, tentando melhorar quando ela não parece interessada. A gente se acostuma, sabe? E ela passa a fazer parte da história. — O dragão fez uma pausa e trocou toda a empolgação por melancolia. — Só que uma hora acaba e... e ela simplesmente não existe mais. Isso me entristece.

Arthur o encarou, solidário.

— Eu te entendo. Mas não pense assim. A gente teve muita sorte, muita mesmo. Já é a nossa sétima jornada. Quinta pessoa diferente. A maioria dos personagens por aí são lidos apenas uma vez e largados para sempre numa estante. Você tem noção disso? Nós tivemos sorte... muita sorte. — O herói respirou fundo e percebeu que estava emocionado. — Lembra quando a aquela garota nos leu pela segunda vez? Foi de longe a nossa melhor atuação. Pelo menos eu acho que foi. Eu lembro que ela terminou gostando da história mais do que na primeira vez.

— É, aquela foi realmente perfeita... — relembrou o dragão, mostrando os dentes afiados com um sorriso involuntário.

— Vamos esperar, é tudo o que a gente pode fazer.

O dragão suspirou, tomando o cuidado de não jogar ar quente no velho amigo, e se aninhou na grama, com a ponta do rabo encostando na cabeça, formando um círculo de escamas.

Arthur deixou as costas caírem para trás, deitando com as mãos entrelaçadas na nuca, e fechou os olhos. O sol incidia diretamente sobre o seu rosto, fazendo-o enxergar manchas vermelhas. O suor agora escorria para dentro da sua orelha, fazendo cócegas no ouvido. Irritado, ele vislumbrou:

— E só de pensar que por duas míseras páginas ele não me larga na cena do beijo...

---

**Motivação**: desafio semanal da página "Gente que escreve", no Facebook. 

**Tema**: o livro esquecido embaixo da cama.

